import type { Incident } from "../types/core.types";

/**
 * Export an array of incidents as a CSV file download.
 */
export function exportIncidentCSV(incidents: Incident[]): void {
  const headers = [
    "ID",
    "Type",
    "Severity",
    "Status",
    "Location",
    "Created At",
    "Updated At",
  ];

  const rows = incidents.map((i) => [
    i.id,
    i.type,
    i.severity,
    i.status,
    i.location?.address ??
      `${i.location?.latitude ?? ""},${i.location?.longitude ?? ""}`,
    i.created_at,
    i.updated_at ?? "",
  ]);

  const csvContent = [
    headers.join(","),
    ...rows.map((row) =>
      row
        .map((cell) => `"${String(cell ?? "").replace(/"/g, '""')}"`)
        .join(","),
    ),
  ].join("\n");

  const blob = new Blob([csvContent], { type: "text/csv;charset=utf-8;" });
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = `beacon-incidents-${new Date().toISOString().slice(0, 10)}.csv`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

/**
 * Print a single incident as a PDF using window.print().
 * Opens a styled print window - no external library required.
 */
export function exportIncidentPDF(incident: Incident): void {
  const printWindow = window.open("", "_blank");
  if (!printWindow) return;

  const severityClass = incident.severity?.toLowerCase() ?? "p3";
  const locationStr =
    incident.location?.address ??
    `${incident.location?.latitude ?? ""}, ${incident.location?.longitude ?? ""}`;

  const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <title>Incident Report - ${incident.id}</title>
  <style>
    body { font-family: system-ui, -apple-system, sans-serif; padding: 2rem; color: #111827; margin: 0; }
    h1 { font-size: 1.5rem; font-weight: 700; margin: 0 0 0.5rem; }
    .badge { display: inline-block; padding: 0.2rem 0.65rem; border-radius: 999px; font-size: 0.75rem; font-weight: 600; }
    .p0 { background: #fee2e2; color: #dc2626; }
    .p1 { background: #ffedd5; color: #ea580c; }
    .p2 { background: #fef9c3; color: #ca8a04; }
    .p3 { background: #dbeafe; color: #2563eb; }
    .meta { color: #6b7280; font-size: 0.875rem; margin-left: 0.5rem; }
    table { width: 100%; border-collapse: collapse; margin-top: 1.5rem; }
    th { text-align: left; padding: 0.5rem 0.75rem; font-weight: 600; color: #6b7280; font-size: 0.75rem; text-transform: uppercase; letter-spacing: 0.05em; border-bottom: 2px solid #e5e7eb; }
    td { padding: 0.6rem 0.75rem; border-bottom: 1px solid #f3f4f6; font-size: 0.875rem; vertical-align: top; }
    tr:last-child td { border-bottom: none; }
    .footer { margin-top: 2rem; font-size: 0.75rem; color: #9ca3af; border-top: 1px solid #e5e7eb; padding-top: 1rem; }
    @media print { body { padding: 1rem; } }
  </style>
</head>
<body>
  <h1>Incident Report</h1>
  <span class="badge ${severityClass}">${incident.severity ?? "-"}</span>
  <span class="meta">${incident.status ?? "-"}</span>
  <table>
    <tr><th>ID</th><td>${incident.id}</td></tr>
    <tr><th>Type</th><td>${incident.type ?? "-"}</td></tr>
    <tr><th>Location</th><td>${locationStr}</td></tr>
    <tr><th>Description</th><td>${incident.description ?? "-"}</td></tr>
    <tr><th>Created</th><td>${new Date(incident.created_at).toLocaleString()}</td></tr>
    ${incident.updated_at ? `<tr><th>Last Updated</th><td>${new Date(incident.updated_at).toLocaleString()}</td></tr>` : ""}
  </table>
  <div class="footer">Generated by Beacon Dashboard &middot; ${new Date().toLocaleString()}</div>
</body>
</html>`;

  printWindow.document.write(html);
  printWindow.document.close();
  printWindow.print();
}
